#!/usr/bin/env php
<?php
/***/

// 站点根目录
define('ROOT_PATH', __DIR__ . '/../');
// 定义项目路径
define('APP_PATH', ROOT_PATH . 'application/');
// 数据绝对路径
define('DATA_PATH', ROOT_PATH . 'data/');
// 缓存时间
define('EYOUCMS_CACHE_TIME', 86400);
// 运行缓存
define('RUNTIME_PATH', DATA_PATH . 'runtime/');
// 序列号
define('DEFAULT_SERIALNUMBER','20180508131400oCWIoa');
// 加载框架引导文件
require __DIR__.'/../core/console.php';
